# Generated by Django 4.2.7 on 2023-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=8)),
                ('allergies', models.CharField(max_length=100, null=True)),
                ('medications', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(default='09:00', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
