# Generated by Django 4.2.7 on 2023-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_patient_delete_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
